from maverick.models import SkillConfig
from maverick.names import (
    DO_CYBERSECURITY_REVIEW,
    DO_DOCS,
    DO_ISSUE_SOLO,
    DO_PULLREQUEST_REVIEW,
    MAV_BLOCK_PROPAGATION,
    MAV_BP_ALERTING,
    MAV_BP_CICD,
    MAV_BP_LOGGING,
    MAV_BP_REMOTE_CODE_REVIEW,
    MAV_CLAUDE_CODE_RECOVERY,
    MAV_CREATE_SOLUTION_DESIGN,
    MAV_CREATE_TASKS,
    MAV_DURABILITY_ON_GH,
    MAV_GIT_WORKFLOW,
    MAV_GITHUB_ISSUE_WORKFLOW,
    MAV_LOCAL_VERIFICATION,
    MAV_MULTI_INSTANCE_COORDINATION,
    MAV_PLAN_EXECUTION,
    MAV_SCOPE_BOUNDARIES,
    MAV_STACKED_PRS,
    MAV_SYSTEMATIC_DEBUGGING,
)

CONFIG = SkillConfig(
    name=DO_ISSUE_SOLO,
    description=(
        "Work on a GitHub issue end-to-end autonomously, only pausing when blocked or when clarification is needed."
    ),
    argument_hint="issue number (e.g., 123)",
    user_invocable=True,
    disable_model_invocation=False,
    depends_on=[
        MAV_SCOPE_BOUNDARIES,
        MAV_MULTI_INSTANCE_COORDINATION,
        MAV_DURABILITY_ON_GH,
        MAV_BLOCK_PROPAGATION,
        MAV_GIT_WORKFLOW,
        MAV_STACKED_PRS,
        MAV_GITHUB_ISSUE_WORKFLOW,
        MAV_CREATE_SOLUTION_DESIGN,
        MAV_CREATE_TASKS,
        MAV_PLAN_EXECUTION,
        MAV_LOCAL_VERIFICATION,
        MAV_BP_CICD,
        MAV_BP_REMOTE_CODE_REVIEW,
        MAV_CLAUDE_CODE_RECOVERY,
        MAV_BP_LOGGING,
        MAV_BP_ALERTING,
        MAV_SYSTEMATIC_DEBUGGING,
        DO_DOCS,
        DO_CYBERSECURITY_REVIEW,
        DO_PULLREQUEST_REVIEW,
    ],
)
